### Site Settings ###
title               : Aman Roy
description         : >-
                      "An entrepreneurial soul stuck in a body of a geek. A personal blog about tech, code and things I experience."
baseurl             : ""                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : aman-roy/aman-roy.github.io     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                        
  - pages/tags.html
  - pages/404.html
  - pages/index.md


### Author Info ###
author:
  name              : Aman Roy
  image             : https://i.ibb.co/Ny11jvM/2020-03-21-09-47-33.png
# behance           : your_username
# dribbble          : your_username
  email             : admin@amanroy.me
  facebook          : amanroy007
  github            : aman-roy
  keybase           : amanroy
# gitlab            : your_username
# instagram         : your_username
  linkedin          : amanroy
# medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
  twitter           : Amanroy_geek
# vimeo             : your_username
# youtube           : your_channel_name


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Disqus ###
disqus: amanroy


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: true                                    # Set false to disable comments

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
